version: 2
project_name: process-compose

builds:
  - id: process-compose
    binary: process-compose
    dir: .
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm
    ldflags:
      - -X github.com/f1bonacc1/process-compose/src/config.Version={{ .Tag }}
      - -X github.com/f1bonacc1/process-compose/src/config.CheckForUpdates=false
      - -X github.com/f1bonacc1/process-compose/src/config.SelfUpdateEnabled=false
      - -X github.com/f1bonacc1/process-compose/src/config.Commit={{ .ShortCommit }}
      - -X github.com/f1bonacc1/process-compose/src/config.Date={{ .CommitDate }}
      - -s -w

archives:
  - id: process-compose
    ids:
      - process-compose
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      mtime: "{{ .CommitDate }}"
    files:
      - src: LICENSE
        info:
          mtime: "{{ .CommitDate }}"
      - src: README.md
        info:
          mtime: "{{ .CommitDate }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  disable: true
